import {
  BathroomWoodenTable,
  BlackMetalLamp,
  CreamCeramicOvalBathtub,
  EgyptianBrowVase,
  FurnitureGreenFabricChair,
  GreenLivingRoomSofa,
  KingSizeMasterBedroom,
  LivingRoomBrownSofa,
  SingleBlueFabricChair1,
  WoodenConsoleTable,
  WorkingChair,
  bathroomsink,
  bathroomsink1,

  // bathroomsink1,
  bathroomsink2,
  bathroomsink3,
  bathroomsink4,
  mirror,
  mirror1,
  mirror2,
  mirror3,
  mirror4,
  shower,
  shower1,
  shower2,
  shower3,
  shower4,
  toilet,
  toilet1,
  toilet2,
  toilet3,
  curtain1,
  curtain2,
  curtain3,
  curtain4,
  vases,
  vases1,
  vases2,
  vases3,
  vases4,
  wallart,
  wallart1,
  wallart2,
  wallart3,
  wallart4,
  bed,
  bed1,
  bed2,
  bed3,
  bed4,
  chair,
  chair1,
  chair2,
  chair3,
  chair4,
  sofa,
  sofa1,
  sofa2,
  sofa3,
  sofa4,
  storage,
  storage1,
  storage2,
  storage3,
  storage4,
  table,
  table1,
  table2,
  table3,
  table4,
  backsplash,
  backsplash1,
  backsplash2,
  backsplash3,
  backsplash4,
  cabinets1,
  cabinets2,
  cabinets3,
  cabinets4,
  countertops,
  countertops1,
  countertops2,
  countertops3,
  countertops4,
  faucets,
  faucets1,
  faucets2,
  faucets3,
  faucets4,
  island,
  island1,
  island2,
  island3,
  island4,
  floorlamps,
  floorlamps1,
  floorlamps2,
  floorlamps3,
  floorlamps4,
  lights,
  lights1,
  lights2,
  lights3,
  lights4,
  outdoorlamps,
  outdoorlamps1,
  outdoorlamps2,
  outdoorlamps3,
  outdoorlamps4,
  tablelamps,
  tablelamps1,
  tablelamps2,
  tablelamps3,
  tablelamps4,
  walllights,
  walllights1,
} from "../assets/export";




export const homeproducts1 = [
  {
    name: "Brown Living Room Sofa",
    image: LivingRoomBrownSofa,
    price: 1200.0,
    id: 1,
    description:
      "Nemo malesuada animi consectetur, cras consectetuer laborum tenetur, cum, lacus nemo imperdiet facilisis! Aute metus, lorem primis anim. Eros dolorem.",
    category: "Living Room",
    filter: "living-room",
  },
  {
    name: "Egyptian Vase",
    image: EgyptianBrowVase,
    id: 2,
    price: 400.0,
    description:
      "Habitasse eaque wisi molestie, mollis pharetra convallis exercitation, distinctio eu arcu fugit nibh donec exercitationem, quisque imperdiet mattis proident cupiditate habitant assumenda. Pariatur minus nibh necessitatibus sociis minim, consectetur dapibus.",
    category: "Home Office",
    filter: "home-office",
  },
  {
    id: 3,
    name: "Green Living Room Sofa",
    image: GreenLivingRoomSofa,
    price: 1200.0,
    description:
      "Habitasse eaque wisi molestie, mollis pharetra convallis exercitation, distinctio eu arcu fugit nibh donec exercitationem, quisque imperdiet mattis proident cupiditate habitant assumenda. Pariatur minus nibh necessitatibus sociis minim, consectetur dapibus.",
    category: "Living Room",
    filter: "living-room",
  },
  {
    id: 4,
    name: "Modern Emerald Fabric Chair",
    image: FurnitureGreenFabricChair,
    price: 860.0,
    description:
      "Habitasse eaque wisi molestie, mollis pharetra convallis exercitation, distinctio eu arcu fugit nibh donec exercitationem, quisque imperdiet mattis proident.",
    category: "Living Room",
    filter: "living-room",
  },
];

export const homeproducts2 = [
  {
    id: 5,
    name: "Bathroom Wooden Table",
    image: BathroomWoodenTable,
    price: 550.0,
    description:
      "Habitasse eaque wisi molestie, mollis pharetra convallis exercitation, distinctio eu arcu fugit nibh donec exercitationem, quisque imperdiet mattis.",
    category: "Bathroom",
    filter: "bathroom",
  },
  {
    id: 6,
    name: "Modern Emerald Fabric Chair",
    image: FurnitureGreenFabricChair,
    price: 860.0,
    description:
      "Habitasse eaque wisi molestie, mollis pharetra convallis exercitation, distinctio eu arcu fugit nibh donec exercitationem, quisque imperdiet mattis proident.",
    category: "Living Room",
    filter: "living-room",
  },
  {
    id: 7,
    name: "Ceramic Oval Bathtub",
    image: CreamCeramicOvalBathtub,
    price: 11200.0,
    description:
      "Nemo malesuada animi consectetur, cras consectetuer laborum tenetur, cum, lacus nemo imperdiet facilisis! Aute metus, lorem primis anim. Eros dolorem.",
    category: "Bathroom",
    filter: "bathroom",
  },
  {
    id: 8,
    name: "Black Metal Lamp",
    image: BlackMetalLamp,
    price: 265.0,
    description:
      "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
    category: "Home Office",
    filter: "home-office",
  },
  {
    id: 9,
    name: "King Size Master Bedroom",
    image: KingSizeMasterBedroom,
    price: 14500.5,
    description:
      "Habitasse eaque wisi molestie, mollis pharetra convallis exercitation, distinctio eu arcu fugit nibh donec exercitationem, quisque imperdiet mattis pr.",
    category: "Bedroom",
    filter: "bedroom",
  },
  {
    id: 10,
    name: "Wooden Console Table",
    image: WoodenConsoleTable,
    price: 724.0,
    description:
      "Nemo malesuada animi consectetur, cras consectetuer laborum tenetur, cum, lacus nemo imperdiet facilisis! Aute metus, lorem primis anim. Eros dolorem.",
    category: "Home Office",
    filter: "home-office",
  },
  {
    id: 11,
    name: "Beige Working Chair With",
    image: WorkingChair,
    price: 784.0,
    description:
      "Habitasse eaque wisi molestie, mollis pharetra convallis exercitation, distinctio eu arcu fugit nibh donec exercitationem, quisque imperdiet mattis proident cupiditate habitant assumenda. Pariatur minus nibh necessitatibus sociis minim, consectetur dapibus.",
    category: "Home Office",
    filter: "home-office",
  },
  {
    id: 12,
    name: "Blue Comfy Fabric Chair",
    image: SingleBlueFabricChair1,
    price: 580.5,
    description:
      "Habitasse eaque wisi molestie, mollis pharetra convallis exercitation, distinctio eu arcu fugit nibh donec exercitationem, quisque imperdiet mattis proident cupiditate habitant assumenda.",
    category: "Bedroom",
    filter: "bedroom",
  },
];




export const bathroomItems = {
  mirrorItems: [
    {
      name: "Bathroom Mirror",
      image: mirror,
      price: 550.0,
      description:
        "The Bathroom Mirror is a chic and versatile enhancement for your space. Featuring a sleek, modern design with a durable frame, it reflects both style and functionality. Available in various shapes and finishes, this mirror not only adds depth to your bathroom but also serves as an essential tool for your daily routines. Its fog-resistant coating ensures clarity even in steamy environments, making it a perfect blend of elegance and practicality for any bathroom.",
      category: "Bathroom",
      filter: "bathroom",
    },
    {
      name: "Bathroom Mirror",
      image: mirror1,
      price: 550.0,
      description:
        "The Bathroom Mirror is a chic and versatile enhancement for your space. Featuring a sleek, modern design with a durable frame, it reflects both style and functionality. Available in various shapes and finishes, this mirror not only adds depth to your bathroom but also serves as an essential tool for your daily routines. Its fog-resistant coating ensures clarity even in steamy environments, making it a perfect blend of elegance and practicality for any bathroom.",
      category: "Bathroom",
      filter: "bathroom",
    },
    {
      name: "Bathroom Mirror",
      image: mirror2,
      price: 550.0,
      description:
        "The Bathroom Mirror is a chic and versatile enhancement for your space. Featuring a sleek, modern design with a durable frame, it reflects both style and functionality. Available in various shapes and finishes, this mirror not only adds depth to your bathroom but also serves as an essential tool for your daily routines. Its fog-resistant coating ensures clarity even in steamy environments, making it a perfect blend of elegance and practicality for any bathroom.",
      category: "Bathroom",
      filter: "bathroom",
    },
    {
      name: "Bathroom Mirror",
      image: mirror3,
      price: 550.0,
      description:
        "The Bathroom Mirror is a chic and versatile enhancement for your space. Featuring a sleek, modern design with a durable frame, it reflects both style and functionality. Available in various shapes and finishes, this mirror not only adds depth to your bathroom but also serves as an essential tool for your daily routines. Its fog-resistant coating ensures clarity even in steamy environments, making it a perfect blend of elegance and practicality for any bathroom.",
      category: "Bathroom",
      filter: "bathroom",
    },
  ],
  sinkItems: [
    {
      name: "Bathroom Sink",
      image: bathroomsink,
      price: 720.99,
      description:
        "The Bathroom Sink is a stylish and functional addition to any bathroom. Crafted from durable materials, it features a sleek design that complements various decor styles. With ample space for daily routines, it includes an integrated faucet and a user-friendly drain system. Available in multiple finishes, this sink combines practicality with aesthetic appeal, making it the perfect centerpiece for your bathroom upgrade.",
      category: "Bathroom",
      filter: "bathroom",
    },
    {
      name: "Bathroom Sink",
      image: bathroomsink1,
      price: 720.99,
      description:
        "The Bathroom Sink is a stylish and functional addition to any bathroom. Crafted from durable materials, it features a sleek design that complements various decor styles. With ample space for daily routines, it includes an integrated faucet and a user-friendly drain system. Available in multiple finishes, this sink combines practicality with aesthetic appeal, making it the perfect centerpiece for your bathroom upgrade.",
      category: "Bathroom",
      filter: "bathroom",
    },
    {
      name: "Bathroom Sink",
      image: bathroomsink2,
      price: 740.99,
      description:
        "The Bathroom Sink is a stylish and functional addition to any bathroom. Crafted from durable materials, it features a sleek design that complements various decor styles. With ample space for daily routines, it includes an integrated faucet and a user-friendly drain system. Available in multiple finishes, this sink combines practicality with aesthetic appeal, making it the perfect centerpiece for your bathroom upgrade.",
      category: "Bathroom",
      filter: "bathroom",
    },
    {
      name: "Bathroom Sink",
      image: bathroomsink3,
      price: 770.99,
      description:
        "The Bathroom Sink is a stylish and functional addition to any bathroom. Crafted from durable materials, it features a sleek design that complements various decor styles. With ample space for daily routines, it includes an integrated faucet and a user-friendly drain system. Available in multiple finishes, this sink combines practicality with aesthetic appeal, making it the perfect centerpiece for your bathroom upgrade.",
      category: "Bathroom",
      filter: "bathroom",
    },
  ],
};


export const furniture = {
  sofaitem: [
    {
      name: "Furniture Sofa",
      image: sofa,
      price: 11200.0,
      description: "The Sofa is a stylish and inviting centerpiece for your living space. Designed for comfort and durability, it offers ample seating and a range of colors and fabrics to suit any decor. Perfect for relaxing, entertaining, or cozy movie nights, this sofa enhances your home’s aesthetic while providing a welcoming atmosphere.",
      category: "Furniture",
      filter: "furnitur",
    },
    {
      name: "Furniture Sofa",
      image: sofa1,
      price: 11200.0,
      description: "The Sofa is a stylish and inviting centerpiece for your living space. Designed for comfort and durability, it offers ample seating and a range of colors and fabrics to suit any decor. Perfect for relaxing, entertaining, or cozy movie nights, this sofa enhances your home’s aesthetic while providing a welcoming atmosphere.",
      category: "Furniture",
      filter: "furnitur",
    },
    {
      name: "Furniture Sofa",
      image: sofa2,
      price: 11200.0,
      description: "The Sofa is a stylish and inviting centerpiece for your living space. Designed for comfort and durability, it offers ample seating and a range of colors and fabrics to suit any decor. Perfect for relaxing, entertaining, or cozy movie nights, this sofa enhances your home’s aesthetic while providing a welcoming atmosphere.",
      category: "Furniture",
      filter: "furnitur",
    },
    {
      name: "Furniture Sofa",
      image: sofa3,
      price: 11200.0,
      description: "The Sofa is a stylish and inviting centerpiece for your living space. Designed for comfort and durability, it offers ample seating and a range of colors and fabrics to suit any decor. Perfect for relaxing, entertaining, or cozy movie nights, this sofa enhances your home’s aesthetic while providing a welcoming atmosphere.",
      category: "Furniture",
      filter: "furnitur",
    },
  ],
  beditem: [
    {
      name: "Furniture Bed",
      image: bed,
      price: 11200.0,
      description: "The Bed is a stylish centerpiece that combines comfort and design. Crafted for durability, it offers a cozy sleeping experience while enhancing your bedroom decor. Available in various styles and sizes, it’s the perfect foundation for restful nights and stylish interiors.",
      category: "Furniture",
      filter: "furnitur",
    },
    {
      name: "Furniture Bed",
      image: bed1,
      price: 11200.0,
      description: "The Bed is a stylish centerpiece that combines comfort and design. Crafted for durability, it offers a cozy sleeping experience while enhancing your bedroom decor. Available in various styles and sizes, it’s the perfect foundation for restful nights and stylish interiors.",
      category: "Furniture",
      filter: "furnitur",
    },
    {
      name: "Furniture Bed",
      image: bed2,
      price: 11200.0,
      description: "The Bed is a stylish centerpiece that combines comfort and design. Crafted for durability, it offers a cozy sleeping experience while enhancing your bedroom decor. Available in various styles and sizes, it’s the perfect foundation for restful nights and stylish interiors.",
      category: "Furniture",
      filter: "furnitur",
    },
    {
      name: "Furniture Bed",
      image: bed3,
      price: 11200.0,
      description: "The Bed is a stylish centerpiece that combines comfort and design. Crafted for durability, it offers a cozy sleeping experience while enhancing your bedroom decor. Available in various styles and sizes, it’s the perfect foundation for restful nights and stylish interiors.",
      category: "Furniture",
      filter: "furnitur",
    },
    // ... Add other furniture items here
  ],
  chairitem: [
    {
      name: "Furniture Chair",
      image: chair4,
      price: 11200.0,
      description: "The Chair is a chic and comfortable seating option that adds flair to any room. Designed for both style and functionality, it offers ergonomic support and a range of finishes to complement your decor. Perfect for relaxing or entertaining, this chair enhances your space with elegance and practicality.",
      category: "Furniture",
      filter: "furnitur",
    },
    {
      name: "Furniture Chair",
      image: chair,
      price: 11200.0,
      description: "The Chair is a chic and comfortable seating option that adds flair to any room. Designed for both style and functionality, it offers ergonomic support and a range of finishes to complement your decor. Perfect for relaxing or entertaining, this chair enhances your space with elegance and practicality.",
      category: "Furniture",
      filter: "furnitur",
    },
    {
      name: "Furniture Chair",
      image: chair1,
      price: 11200.0,
      description: "The Chair is a chic and comfortable seating option that adds flair to any room. Designed for both style and functionality, it offers ergonomic support and a range of finishes to complement your decor. Perfect for relaxing or entertaining, this chair enhances your space with elegance and practicality.",
      category: "Furniture",
      filter: "furnitur",
    },
    {
      name: "Furniture Chair",
      image: chair2,
      price: 11200.0,
      description: "The Chair is a chic and comfortable seating option that adds flair to any room. Designed for both style and functionality, it offers ergonomic support and a range of finishes to complement your decor. Perfect for relaxing or entertaining, this chair enhances your space with elegance and practicality.",
      category: "Furniture",
      filter: "furnitur",
    },

  ],
  storageitem: [
    {
      name: "Furniture Storage",
      image: storage1,
      price: 11200.0,
      description: "The Storage Solution is a practical and stylish way to keep your space organized. Featuring various sizes and designs, it offers ample room for all your essentials while enhancing your decor. Perfect for any room, this storage option combines functionality with aesthetic appeal, making it easy to declutter and beautify your home.",
      category: "Furniture",
      filter: "furnitur",
    },
    {
      name: "Furniture Storage",
      image: storage2,
      price: 11200.0,
      description: "The Storage Solution is a practical and stylish way to keep your space organized. Featuring various sizes and designs, it offers ample room for all your essentials while enhancing your decor. Perfect for any room, this storage option combines functionality with aesthetic appeal, making it easy to declutter and beautify your home.",
      category: "Furniture",
      filter: "furnitur",
    },
    {
      name: "Furniture Storage",
      image: storage3,
      price: 11200.0,
      description: "The Storage Solution is a practical and stylish way to keep your space organized. Featuring various sizes and designs, it offers ample room for all your essentials while enhancing your decor. Perfect for any room, this storage option combines functionality with aesthetic appeal, making it easy to declutter and beautify your home.",
      category: "Furniture",
      filter: "furnitur",
    },
    {
      name: "Furniture Storage",
      image: storage4,
      price: 11200.0,
      description: "The Storage Solution is a practical and stylish way to keep your space organized. Featuring various sizes and designs, it offers ample room for all your essentials while enhancing your decor. Perfect for any room, this storage option combines functionality with aesthetic appeal, making it easy to declutter and beautify your home.",
      category: "Furniture",
      filter: "furnitur",
    },
    // ... Add other storage items here
  ],
  tablesitem: [
    {
      name: "Furniture Tables",
      image: table,
      price: 11200.0,
      description: "The Table is a versatile piece that serves as the heart of your space. Whether for dining, working, or displaying decor, it combines style and functionality. Available in various materials and designs, this table enhances your decor while providing a practical surface for everyday use. Perfect for gatherings or quiet moments, it adds charm and utility to any room.",
      category: "Furniture",
      filter: "furnitur",
    },
    {
      name: "Furniture Tables",
      image: table1,
      price: 11200.0,
      description: "The Table is a versatile piece that serves as the heart of your space. Whether for dining, working, or displaying decor, it combines style and functionality. Available in various materials and designs, this table enhances your decor while providing a practical surface for everyday use. Perfect for gatherings or quiet moments, it adds charm and utility to any room.",
      category: "Furniture",
      filter: "furnitur",
    },
    {
      name: "Furniture Tables",
      image: table2,
      price: 11200.0,
      description: "The Table is a versatile piece that serves as the heart of your space. Whether for dining, working, or displaying decor, it combines style and functionality. Available in various materials and designs, this table enhances your decor while providing a practical surface for everyday use. Perfect for gatherings or quiet moments, it adds charm and utility to any room.",
      category: "Furniture",
      filter: "furnitur",
    },
    {
      name: "Furniture Tables",
      image: table3,
      price: 11200.0,
      description: "The Table is a versatile piece that serves as the heart of your space. Whether for dining, working, or displaying decor, it combines style and functionality. Available in various materials and designs, this table enhances your decor while providing a practical surface for everyday use. Perfect for gatherings or quiet moments, it adds charm and utility to any room.",
      category: "Furniture",
      filter: "furnitur",
    },
    // ... Add other table items here
  ],
};



export const sofa54= [



  {
    name: "Green Living Room Sofa",
    // image: sofa2,
    price: 1200.0,
    description:
      "Habitasse eaque wisi molestie, mollis pharetra convallis exercitation, distinctio eu arcu fugit nibh donec exercitationem, quisque imperdiet mattis proident cupiditate habitant assumenda. Pariatur minus nibh necessitatibus sociis minim, consectetur dapibus.",
    category: "Living Room",
    filter: "living-room",
  },
  {
    name: "Brown Living Room Sofa",
    // image: LivingRoomBrownSofa,
    price: 1200.0,
    description:
      "Nemo malesuada animi consectetur, cras consectetuer laborum tenetur, cum, lacus nemo imperdiet facilisis! Aute metus, lorem primis anim. Eros dolorem.",
    category: "Living Room",
    filter: "living-room",
  },

  // furniture beds


  {
    name: "Furniture Bed",
    image: bed,
    price: 11200.0,
    description: "The Bed is a stylish centerpiece that combines comfort and design. Crafted for durability, it offers a cozy sleeping experience while enhancing your bedroom decor. Available in various styles and sizes, it’s the perfect foundation for restful nights and stylish interiors.",
    category: "Furniture",
    filter: "furnitur",
  },
  {
    name: "Furniture Bed",
    image: bed1,
    price: 11200.0,
    description: "The Bed is a stylish centerpiece that combines comfort and design. Crafted for durability, it offers a cozy sleeping experience while enhancing your bedroom decor. Available in various styles and sizes, it’s the perfect foundation for restful nights and stylish interiors.",
    category: "Furniture",
    filter: "furnitur",
  },
  {
    name: "Furniture Bed",
    image: bed2,
    price: 11200.0,
    description: "The Bed is a stylish centerpiece that combines comfort and design. Crafted for durability, it offers a cozy sleeping experience while enhancing your bedroom decor. Available in various styles and sizes, it’s the perfect foundation for restful nights and stylish interiors.",
    category: "Furniture",
    filter: "furnitur",
  },
  {
    name: "Furniture Bed",
    image: bed3,
    price: 11200.0,
    description: "The Bed is a stylish centerpiece that combines comfort and design. Crafted for durability, it offers a cozy sleeping experience while enhancing your bedroom decor. Available in various styles and sizes, it’s the perfect foundation for restful nights and stylish interiors.",
    category: "Furniture",
    filter: "furnitur",
  },
  {
    name: "Furniture Bed",
    image: bed4,
    price: 11200.0,
    description: "The Bed is a stylish centerpiece that combines comfort and design. Crafted for durability, it offers a cozy sleeping experience while enhancing your bedroom decor. Available in various styles and sizes, it’s the perfect foundation for restful nights and stylish interiors.",
    category: "Furniture",
    filter: "furnitur",
  },

  // furniture chair
  {
    name: "Furniture Chair",
    image: chair4,
    price: 11200.0,
    description: "The Chair is a chic and comfortable seating option that adds flair to any room. Designed for both style and functionality, it offers ergonomic support and a range of finishes to complement your decor. Perfect for relaxing or entertaining, this chair enhances your space with elegance and practicality.",
    category: "Furniture",
    filter: "furnitur",
  },
  {
    name: "Furniture Chair",
    image: chair,
    price: 11200.0,
    description: "The Chair is a chic and comfortable seating option that adds flair to any room. Designed for both style and functionality, it offers ergonomic support and a range of finishes to complement your decor. Perfect for relaxing or entertaining, this chair enhances your space with elegance and practicality.",
    category: "Furniture",
    filter: "furnitur",
  },
  {
    name: "Furniture Chair",
    image: chair1,
    price: 11200.0,
    description: "The Chair is a chic and comfortable seating option that adds flair to any room. Designed for both style and functionality, it offers ergonomic support and a range of finishes to complement your decor. Perfect for relaxing or entertaining, this chair enhances your space with elegance and practicality.",
    category: "Furniture",
    filter: "furnitur",
  },
  {
    name: "Furniture Chair",
    image: chair2,
    price: 11200.0,
    description: "The Chair is a chic and comfortable seating option that adds flair to any room. Designed for both style and functionality, it offers ergonomic support and a range of finishes to complement your decor. Perfect for relaxing or entertaining, this chair enhances your space with elegance and practicality.",
    category: "Furniture",
    filter: "furnitur",
  },
  {
    name: "Furniture Chair",
    image: chair3,
    price: 11200.0,
    description: "The Chair is a chic and comfortable seating option that adds flair to any room. Designed for both style and functionality, it offers ergonomic support and a range of finishes to complement your decor. Perfect for relaxing or entertaining, this chair enhances your space with elegance and practicality.",
    category: "Furniture",
    filter: "furnitur",
  },

  // furniture sofas
  {
    name: "Furniture Sofa",
    // image: sofa,
    //   price: 11200.0,
    description: "The Sofa is a stylish and inviting centerpiece for your living space. Designed for comfort and durability, it offers ample seating and a range of colors and fabrics to suit any decor. Perfect for relaxing, entertaining, or cozy movie nights, this sofa enhances your home’s aesthetic while providing a welcoming atmosphere.",
    category: "Furniture",
    filter: "furnitur",
  },
  {
    name: "Furniture Sofa",
    image: sofa1,
    price: 11200.0,
    description: "The Sofa is a stylish and inviting centerpiece for your living space. Designed for comfort and durability, it offers ample seating and a range of colors and fabrics to suit any decor. Perfect for relaxing, entertaining, or cozy movie nights, this sofa enhances your home’s aesthetic while providing a welcoming atmosphere.",
    category: "Furniture",
    filter: "furnitur",
  },
  {
    name: "Furniture Sofa",
    image: sofa2,
    price: 11200.0,
    description: "The Sofa is a stylish and inviting centerpiece for your living space. Designed for comfort and durability, it offers ample seating and a range of colors and fabrics to suit any decor. Perfect for relaxing, entertaining, or cozy movie nights, this sofa enhances your home’s aesthetic while providing a welcoming atmosphere.",
    category: "Furniture",
    filter: "furnitur",
  },
  {
    name: "Furniture Sofa",
    image: sofa3,
    price: 11200.0,
    description: "The Sofa is a stylish and inviting centerpiece for your living space. Designed for comfort and durability, it offers ample seating and a range of colors and fabrics to suit any decor. Perfect for relaxing, entertaining, or cozy movie nights, this sofa enhances your home’s aesthetic while providing a welcoming atmosphere.",
    category: "Furniture",
    filter: "furnitur",
  },
  {
    name: "Furniture Sofa",
    image: sofa4,
    price: 11200.0,
    description: "The Sofa is a stylish and inviting centerpiece for your living space. Designed for comfort and durability, it offers ample seating and a range of colors and fabrics to suit any decor. Perfect for relaxing, entertaining, or cozy movie nights, this sofa enhances your home’s aesthetic while providing a welcoming atmosphere.",
    category: "Furniture",
    filter: "furnitur",
  },

  // furniture storage
  {
    name: "Furniture Storage",
    image: storage,
    price: 11200.0,
    description: "The Storage Solution is a practical and stylish way to keep your space organized. Featuring various sizes and designs, it offers ample room for all your essentials while enhancing your decor. Perfect for any room, this storage option combines functionality with aesthetic appeal, making it easy to declutter and beautify your home.",
    category: "Furniture",
    filter: "furnitur",
  },
  {
    name: "Furniture Storage",
    image: storage1,
    price: 11200.0,
    description: "The Storage Solution is a practical and stylish way to keep your space organized. Featuring various sizes and designs, it offers ample room for all your essentials while enhancing your decor. Perfect for any room, this storage option combines functionality with aesthetic appeal, making it easy to declutter and beautify your home.",
    category: "Furniture",
    filter: "furnitur",
  },
  {
    name: "Furniture Storage",
    image: storage2,
    price: 11200.0,
    description: "The Storage Solution is a practical and stylish way to keep your space organized. Featuring various sizes and designs, it offers ample room for all your essentials while enhancing your decor. Perfect for any room, this storage option combines functionality with aesthetic appeal, making it easy to declutter and beautify your home.",
    category: "Furniture",
    filter: "furnitur",
  },
  {
    name: "Furniture Storage",
    image: storage3,
    price: 11200.0,
    description: "The Storage Solution is a practical and stylish way to keep your space organized. Featuring various sizes and designs, it offers ample room for all your essentials while enhancing your decor. Perfect for any room, this storage option combines functionality with aesthetic appeal, making it easy to declutter and beautify your home.",
    category: "Furniture",
    filter: "furnitur",
  },
  {
    name: "Furniture Storage",
    image: storage4,
    price: 11200.0,
    description: "The Storage Solution is a practical and stylish way to keep your space organized. Featuring various sizes and designs, it offers ample room for all your essentials while enhancing your decor. Perfect for any room, this storage option combines functionality with aesthetic appeal, making it easy to declutter and beautify your home.",
    category: "Furniture",
    filter: "furnitur",
  },


  {
    name: "Furniture Tables",
    image: table,
    price: 11200.0,
    description: "The Table is a versatile piece that serves as the heart of your space. Whether for dining, working, or displaying decor, it combines style and functionality. Available in various materials and designs, this table enhances your decor while providing a practical surface for everyday use. Perfect for gatherings or quiet moments, it adds charm and utility to any room.",
    category: "Furniture",
    filter: "furnitur",
  },
  {
    name: "Furniture Tables",
    image: table1,
    price: 11200.0,
    description: "The Table is a versatile piece that serves as the heart of your space. Whether for dining, working, or displaying decor, it combines style and functionality. Available in various materials and designs, this table enhances your decor while providing a practical surface for everyday use. Perfect for gatherings or quiet moments, it adds charm and utility to any room.",
    category: "Furniture",
    filter: "furnitur",
  },
  {
    name: "Furniture Tables",
    image: table2,
    price: 11200.0,
    description: "The Table is a versatile piece that serves as the heart of your space. Whether for dining, working, or displaying decor, it combines style and functionality. Available in various materials and designs, this table enhances your decor while providing a practical surface for everyday use. Perfect for gatherings or quiet moments, it adds charm and utility to any room.",
    category: "Furniture",
    filter: "furnitur",
  },
  {
    name: "Furniture Tables",
    image: table3,
    price: 11200.0,
    description: "The Table is a versatile piece that serves as the heart of your space. Whether for dining, working, or displaying decor, it combines style and functionality. Available in various materials and designs, this table enhances your decor while providing a practical surface for everyday use. Perfect for gatherings or quiet moments, it adds charm and utility to any room.",
    category: "Furniture",
    filter: "furnitur",
  },
  {
    name: "Furniture Tables",
    image: table4,
    price: 11200.0,
    description: "The Table is a versatile piece that serves as the heart of your space. Whether for dining, working, or displaying decor, it combines style and functionality. Available in various materials and designs, this table enhances your decor while providing a practical surface for everyday use. Perfect for gatherings or quiet moments, it adds charm and utility to any room.",
    category: "Furniture",
    filter: "furnitur",
  },
]

export const products = [
    {
        name: "bathroom sink",
          image: bathroomsink4,
        price: 780.99,
        description:
            "The Bathroom Sink is a stylish and functional addition to any bathroom. Crafted from durable materials, it features a sleek design that complements various decor styles. With ample space for daily routines, it includes an integrated faucet and a user-friendly drain system. Available in multiple finishes, this sink combines practicality with aesthetic appeal, making it the perfect centerpiece for your bathroom upgrade.",
        category: "Bathroom",
        filter: "bathroom",
    },

    {
        name: "bathroom mirror",
          image:  mirror,
        price: 550.0,
        description:
            "The Bathroom Mirror is a chic and versatile enhancement for your space. Featuring a sleek, modern design with a durable frame, it reflects both style and functionality. Available in various shapes and finishes, this mirror not only adds depth to your bathroom but also serves as an essential tool for your daily routines. Its fog-resistant coating ensures clarity even in steamy environments, making it a perfect blend of elegance and practicality for any bathroom.",
        category: "Bathroom",
        filter: "bathroom",
    },
    {
        name: "bathroom mirror",
          image:  mirror1,
        price: 550.0,
        description:
            "The Bathroom Mirror is a chic and versatile enhancement for your space. Featuring a sleek, modern design with a durable frame, it reflects both style and functionality. Available in various shapes and finishes, this mirror not only adds depth to your bathroom but also serves as an essential tool for your daily routines. Its fog-resistant coating ensures clarity even in steamy environments, making it a perfect blend of elegance and practicality for any bathroom.",
        category: "Bathroom",
        filter: "bathroom",
    },
    {
        name: "bathroom mirror",
          image:  mirror2,
        price: 550.0,
        description:
            "The Bathroom Mirror is a chic and versatile enhancement for your space. Featuring a sleek, modern design with a durable frame, it reflects both style and functionality. Available in various shapes and finishes, this mirror not only adds depth to your bathroom but also serves as an essential tool for your daily routines. Its fog-resistant coating ensures clarity even in steamy environments, making it a perfect blend of elegance and practicality for any bathroom.",
        category: "Bathroom",
        filter: "bathroom",
    },
    {
        name: "bathroom mirror",
          image:  mirror3,
        price: 550.0,
        description:
            "The Bathroom Mirror is a chic and versatile enhancement for your space. Featuring a sleek, modern design with a durable frame, it reflects both style and functionality. Available in various shapes and finishes, this mirror not only adds depth to your bathroom but also serves as an essential tool for your daily routines. Its fog-resistant coating ensures clarity even in steamy environments, making it a perfect blend of elegance and practicality for any bathroom.",
        category: "Bathroom",
        filter: "bathroom",
    },
    {
        name: "bathroom mirror",
          image:  mirror4,
        price: 550.0,
        description:
            "The Bathroom Mirror is a chic and versatile enhancement for your space. Featuring a sleek, modern design with a durable frame, it reflects both style and functionality. Available in various shapes and finishes, this mirror not only adds depth to your bathroom but also serves as an essential tool for your daily routines. Its fog-resistant coating ensures clarity even in steamy environments, making it a perfect blend of elegance and practicality for any bathroom.",
        category: "Bathroom",
        filter: "bathroom",
    },

    // bathroom showers
    {
        name: "bathroom showers",
          image: shower,
        price: 490,
        description: "The Bathroom Shower is a luxurious upgrade for your bathing experience. Designed with both style and functionality in mind, it features a spacious interior and high-quality materials that ensure durability and easy maintenance. Choose from various styles, including rainfall and handheld options, to customize your showering experience. With efficient water flow and optional built-in storage, this shower transforms your bathroom into a serene oasis, perfect for relaxation and rejuvenation.",
        category: "Bathroom",
        filter: "bathroom",
    },
    {
        name: "bathroom showers",
          image: shower1,
        price: 140,
        description: "The Bathroom Shower is a luxurious upgrade for your bathing experience. Designed with both style and functionality in mind, it features a spacious interior and high-quality materials that ensure durability and easy maintenance. Choose from various styles, including rainfall and handheld options, to customize your showering experience. With efficient water flow and optional built-in storage, this shower transforms your bathroom into a serene oasis, perfect for relaxation and rejuvenation.",
        category: "Bathroom",
        filter: "bathroom",
    },
    {
        name: "bathroom showers",
          image: shower2,
        price: 140,
        description: "The Bathroom Shower is a luxurious upgrade for your bathing experience. Designed with both style and functionality in mind, it features a spacious interior and high-quality materials that ensure durability and easy maintenance. Choose from various styles, including rainfall and handheld options, to customize your showering experience. With efficient water flow and optional built-in storage, this shower transforms your bathroom into a serene oasis, perfect for relaxation and rejuvenation.",
        category: "Bathroom",
        filter: "bathroom",
    },
    {
        name: "bathroom showers",
          image: shower3,
        price: 140,
        description: "The Bathroom Shower is a luxurious upgrade for your bathing experience. Designed with both style and functionality in mind, it features a spacious interior and high-quality materials that ensure durability and easy maintenance. Choose from various styles, including rainfall and handheld options, to customize your showering experience. With efficient water flow and optional built-in storage, this shower transforms your bathroom into a serene oasis, perfect for relaxation and rejuvenation.",
        category: "Bathroom",
        filter: "bathroom",
    },
    {
        name: "bathroom showers",
          image: shower4,
        price: 190,
        description: "The Bathroom Shower is a luxurious upgrade for your bathing experience. Designed with both style and functionality in mind, it features a spacious interior and high-quality materials that ensure durability and easy maintenance. Choose from various styles, including rainfall and handheld options, to customize your showering experience. With efficient water flow and optional built-in storage, this shower transforms your bathroom into a serene oasis, perfect for relaxation and rejuvenation.",
        category: "Bathroom",
        filter: "bathroom",
    },

    // bathroom toilets
    {
        name: "Bathroom toilets",
          image: toilet,
        price: 1490,
        description: "The Bathroom Toilet is a blend of comfort and efficiency, designed to enhance your bathroom experience. Featuring a sleek, modern silhouette, it fits seamlessly into any decor. With a powerful flushing system for optimal performance and water-saving technology, it ensures eco-friendliness without compromising on quality. Easy to clean and maintain, this toilet provides reliability and style, making it an essential fixture for any bathroom upgrade.",
        category: "Bathroom",
        filter: "bathroom",
    },
    {
        name: "Bathroom toilets",
          image: toilet1,
        price: 1490,
        description: "The Bathroom Toilet is a blend of comfort and efficiency, designed to enhance your bathroom experience. Featuring a sleek, modern silhouette, it fits seamlessly into any decor. With a powerful flushing system for optimal performance and water-saving technology, it ensures eco-friendliness without compromising on quality. Easy to clean and maintain, this toilet provides reliability and style, making it an essential fixture for any bathroom upgrade.",
        category: "Bathroom",
        filter: "bathroom",
    },
    {
        name: "Bathroom toilets",
          image: toilet2,
        price: 1490,
        description: "The Bathroom Toilet is a blend of comfort and efficiency, designed to enhance your bathroom experience. Featuring a sleek, modern silhouette, it fits seamlessly into any decor. With a powerful flushing system for optimal performance and water-saving technology, it ensures eco-friendliness without compromising on quality. Easy to clean and maintain, this toilet provides reliability and style, making it an essential fixture for any bathroom upgrade.",
        category: "Bathroom",
        filter: "bathroom",
    },
    {
        name: "Bathroom toilets",
          image: toilet3,
        price: 1490,
        description: "The Bathroom Toilet is a blend of comfort and efficiency, designed to enhance your bathroom experience. Featuring a sleek, modern silhouette, it fits seamlessly into any decor. With a powerful flushing system for optimal performance and water-saving technology, it ensures eco-friendliness without compromising on quality. Easy to clean and maintain, this toilet provides reliability and style, making it an essential fixture for any bathroom upgrade.",
        category: "Bathroom",
        filter: "bathroom",
    },
    {
        name: "Bathroom toilets",
          // image: toilet4,
        price: 1490,
        description: "The Bathroom Toilet is a blend of comfort and efficiency, designed to enhance your bathroom experience. Featuring a sleek, modern silhouette, it fits seamlessly into any decor. With a powerful flushing system for optimal performance and water-saving technology, it ensures eco-friendliness without compromising on quality. Easy to clean and maintain, this toilet provides reliability and style, making it an essential fixture for any bathroom upgrade.",
        category: "Bathroom",
        filter: "bathroom",
    },

    // bathroom vanaties
    {
        name: "bathroom vanities",
          // image: vanities,
        price: 570.0,
        description: "The Bathroom Vanity is a perfect combination of style and storage, elevating the functionality of your bathroom. Crafted with high-quality materials, it features a sleek design with ample countertop space and integrated sinks. Multiple drawers and cabinets provide convenient storage for toiletries and essentials, keeping your space organized. Available in various finishes and styles, this vanity not only enhances your bathroom's aesthetics but also offers practical solutions for everyday use.",
        category: "Bathroom",
        filter: "bathroom",
    },
    {
        name: "bathroom vanities",
          image: cabinets4,
        price: 560.0,
        description: "The Bathroom Vanity is a perfect combination of style and storage, elevating the functionality of your bathroom. Crafted with high-quality materials, it features a sleek design with ample countertop space and integrated sinks. Multiple drawers and cabinets provide convenient storage for toiletries and essentials, keeping your space organized. Available in various finishes and styles, this vanity not only enhances your bathroom's aesthetics but also offers practical solutions for everyday use.",
        category: "Bathroom",
        filter: "bathroom",
    },
    {
        name: "bathroom vanities",
          image: cabinets2,
        price: 552.0,
        description: "The Bathroom Vanity is a perfect combination of style and storage, elevating the functionality of your bathroom. Crafted with high-quality materials, it features a sleek design with ample countertop space and integrated sinks. Multiple drawers and cabinets provide convenient storage for toiletries and essentials, keeping your space organized. Available in various finishes and styles, this vanity not only enhances your bathroom's aesthetics but also offers practical solutions for everyday use.",
        category: "Bathroom",
        filter: "bathroom",
    },
    {
        name: "bathroom vanities",
          image: cabinets1,
        price: 553.0,
        description: "The Bathroom Vanity is a perfect combination of style and storage, elevating the functionality of your bathroom. Crafted with high-quality materials, it features a sleek design with ample countertop space and integrated sinks. Multiple drawers and cabinets provide convenient storage for toiletries and essentials, keeping your space organized. Available in various finishes and styles, this vanity not only enhances your bathroom's aesthetics but also offers practical solutions for everyday use.",
        category: "Bathroom",
        filter: "bathroom",
    },
    {
        name: "bathroom vanities",
          image: cabinets3,
        price: 559.0,
        description: "The Bathroom Vanity is a perfect combination of style and storage, elevating the functionality of your bathroom. Crafted with high-quality materials, it features a sleek design with ample countertop space and integrated sinks. Multiple drawers and cabinets provide convenient storage for toiletries and essentials, keeping your space organized. Available in various finishes and styles, this vanity not only enhances your bathroom's aesthetics but also offers practical solutions for everyday use.",
        category: "Bathroom",
        filter: "bathroom",
    },

    // decor curtains
    {
        name: "Decor curtains",
          // image:  curtain,
        price: 504.0,
        description: "The Decorative Curtains are a stylish addition to any room, enhancing your decor while providing privacy and light control. Crafted from high-quality fabrics, they feature vibrant colors and intricate patterns that elevate your space. Available in various lengths and styles, these curtains effortlessly complement your interior design, whether it's modern, traditional, or eclectic. Easy to hang and maintain, they add a touch of elegance and warmth, making your home feel inviting and complete.",
        category: "Decor",
        filter: "decor",
    },
    {
        name: "Decor curtains",
          image:  curtain1,
        price: 504.0,
        description: "The Decorative Curtains are a stylish addition to any room, enhancing your decor while providing privacy and light control. Crafted from high-quality fabrics, they feature vibrant colors and intricate patterns that elevate your space. Available in various lengths and styles, these curtains effortlessly complement your interior design, whether it's modern, traditional, or eclectic. Easy to hang and maintain, they add a touch of elegance and warmth, making your home feel inviting and complete.",
        category: "Decor",
        filter: "decor",
    },
    {
        name: "Decor curtains",
          image:  curtain2,
        price: 504.0,
        description: "The Decorative Curtains are a stylish addition to any room, enhancing your decor while providing privacy and light control. Crafted from high-quality fabrics, they feature vibrant colors and intricate patterns that elevate your space. Available in various lengths and styles, these curtains effortlessly complement your interior design, whether it's modern, traditional, or eclectic. Easy to hang and maintain, they add a touch of elegance and warmth, making your home feel inviting and complete.",
        category: "Decor",
        filter: "decor",
    },
    {
        name: "Decor curtains",
          image:  curtain3,
        price: 504.0,
        description: "The Decorative Curtains are a stylish addition to any room, enhancing your decor while providing privacy and light control. Crafted from high-quality fabrics, they feature vibrant colors and intricate patterns that elevate your space. Available in various lengths and styles, these curtains effortlessly complement your interior design, whether it's modern, traditional, or eclectic. Easy to hang and maintain, they add a touch of elegance and warmth, making your home feel inviting and complete.",
        category: "Decor",
        filter: "decor",
    },
    {
        name: "Decor curtains",
          image:  curtain4,
        price: 504.0,
        description: "The Decorative Curtains are a stylish addition to any room, enhancing your decor while providing privacy and light control. Crafted from high-quality fabrics, they feature vibrant colors and intricate patterns that elevate your space. Available in various lengths and styles, these curtains effortlessly complement your interior design, whether it's modern, traditional, or eclectic. Easy to hang and maintain, they add a touch of elegance and warmth, making your home feel inviting and complete.",
        category: "Decor",
        filter: "decor",
    },

    // decore rugs
    {
        name: "Decor rugs",
        //   image: rugs,
        //   price: 504.0,
        description: "The Decorative Rug is a versatile accent that transforms any space with warmth and style. Crafted from high-quality materials, it features vibrant colors and intricate patterns that enhance your home decor. Perfect for living rooms, bedrooms, or entryways, this rug adds comfort underfoot while also serving as a focal point in your design scheme. Easy to clean and maintain, it combines practicality with aesthetic appeal, making it an essential element for creating a cozy and inviting atmosphere.",
        category: "Decor",
        filter: "decor",
    },
    {
        name: "Decor rugs",
          // image: rugs1,
        price: 504.0,
        description: "The Decorative Rug is a versatile accent that transforms any space with warmth and style. Crafted from high-quality materials, it features vibrant colors and intricate patterns that enhance your home decor. Perfect for living rooms, bedrooms, or entryways, this rug adds comfort underfoot while also serving as a focal point in your design scheme. Easy to clean and maintain, it combines practicality with aesthetic appeal, making it an essential element for creating a cozy and inviting atmosphere.",
        category: "Decor",
        filter: "decor",
    },
    {
        name: "Decor rugs",
          // image: rugs2,
        price: 504.0,
        description: "The Decorative Rug is a versatile accent that transforms any space with warmth and style. Crafted from high-quality materials, it features vibrant colors and intricate patterns that enhance your home decor. Perfect for living rooms, bedrooms, or entryways, this rug adds comfort underfoot while also serving as a focal point in your design scheme. Easy to clean and maintain, it combines practicality with aesthetic appeal, making it an essential element for creating a cozy and inviting atmosphere.",
        category: "Decor",
        filter: "decor",
    },
    {
        name: "Decor rugs",
          // image: rugs3,
        price: 504.0,
        description: "The Decorative Rug is a versatile accent that transforms any space with warmth and style. Crafted from high-quality materials, it features vibrant colors and intricate patterns that enhance your home decor. Perfect for living rooms, bedrooms, or entryways, this rug adds comfort underfoot while also serving as a focal point in your design scheme. Easy to clean and maintain, it combines practicality with aesthetic appeal, making it an essential element for creating a cozy and inviting atmosphere.",
        category: "Decor",
        filter: "decor",
    },
    {
        name: "Decor rugs",
          // image: rugs4,
        price: 504.0,
        description: "The Decorative Rug is a versatile accent that transforms any space with warmth and style. Crafted from high-quality materials, it features vibrant colors and intricate patterns that enhance your home decor. Perfect for living rooms, bedrooms, or entryways, this rug adds comfort underfoot while also serving as a focal point in your design scheme. Easy to clean and maintain, it combines practicality with aesthetic appeal, making it an essential element for creating a cozy and inviting atmosphere.",
        category: "Decor",
        filter: "decor",
    },

    // decore vases
    {
        name: "Decor vases",
          image: vases,
        price: 11200.0,
        description: "The Decorative Vase is a stunning accent piece that adds elegance to any space. Crafted from quality materials, it features unique designs and finishes that enhance your decor. Perfect for holding fresh flowers or standing alone as a statement piece, this vase brings a touch of style and personality to your home.",
        category: "Decor",
        filter: "decor",
    },
    {
        name: "Decor vases",
          image: vases1,
        price: 11200.0,
        description: "The Decorative Vase is a stunning accent piece that adds elegance to any space. Crafted from quality materials, it features unique designs and finishes that enhance your decor. Perfect for holding fresh flowers or standing alone as a statement piece, this vase brings a touch of style and personality to your home.",
        category: "Decor",
        filter: "decor",
    },
    {
        name: "Decor vases",
          image: vases2,
        price: 11200.0,
        description: "The Decorative Vase is a stunning accent piece that adds elegance to any space. Crafted from quality materials, it features unique designs and finishes that enhance your decor. Perfect for holding fresh flowers or standing alone as a statement piece, this vase brings a touch of style and personality to your home.",
        category: "Decor",
        filter: "decor",
    },
    {
        name: "Decor vases",
          image: vases3,
        price: 11200.0,
        description: "The Decorative Vase is a stunning accent piece that adds elegance to any space. Crafted from quality materials, it features unique designs and finishes that enhance your decor. Perfect for holding fresh flowers or standing alone as a statement piece, this vase brings a touch of style and personality to your home.",
        category: "Decor",
        filter: "decor",
    },
    {
        name: "Decor vases",
          image: vases4,
        price: 11200.0,
        description: "The Decorative Vase is a stunning accent piece that adds elegance to any space. Crafted from quality materials, it features unique designs and finishes that enhance your decor. Perfect for holding fresh flowers or standing alone as a statement piece, this vase brings a touch of style and personality to your home.",
        category: "Decor",
        filter: "decor",
    },

    //  decore wall art
    {
        name: "Decor wall art",
          image: wallart,
        price: 11200.0,
        description: "The Wall Art is a captivating addition that elevates your interior decor. Featuring unique designs and vibrant colors, it brings personality and character to any room. Perfect for complementing your style, this artwork transforms blank walls into eye-catching focal points, creating a warm and inviting atmosphere in your home.",
        category: "Decor",
        filter: "decor",
    },
    {
        name: "Decor wall art",
          image: wallart1,
        price: 11200.0,
        description: "The Wall Art is a captivating addition that elevates your interior decor. Featuring unique designs and vibrant colors, it brings personality and character to any room. Perfect for complementing your style, this artwork transforms blank walls into eye-catching focal points, creating a warm and inviting atmosphere in your home.",
        category: "Decor",
        filter: "decor",
    },
    {
        name: "Decor wall art",
          image: wallart2,
        price: 11200.0,
        description: "The Wall Art is a captivating addition that elevates your interior decor. Featuring unique designs and vibrant colors, it brings personality and character to any room. Perfect for complementing your style, this artwork transforms blank walls into eye-catching focal points, creating a warm and inviting atmosphere in your home.",
        category: "Decor",
        filter: "decor",
    },
    {
        name: "Decor wall art",
          image: wallart3,
        price: 11200.0,
        description: "The Wall Art is a captivating addition that elevates your interior decor. Featuring unique designs and vibrant colors, it brings personality and character to any room. Perfect for complementing your style, this artwork transforms blank walls into eye-catching focal points, creating a warm and inviting atmosphere in your home.",
        category: "Decor",
        filter: "decor",
    },
    {
        name: "Decor wall art",
          image: wallart4,
        price: 11200.0,
        description: "The Wall Art is a captivating addition that elevates your interior decor. Featuring unique designs and vibrant colors, it brings personality and character to any room. Perfect for complementing your style, this artwork transforms blank walls into eye-catching focal points, creating a warm and inviting atmosphere in your home.",
        category: "Decor",
        filter: "decor",
    },

    // furniture beds
    {
        name: "Furniture Bed",
        //   image: bed,
        //   price: 11200.0,
        description: "The Bed is a stylish centerpiece that combines comfort and design. Crafted for durability, it offers a cozy sleeping experience while enhancing your bedroom decor. Available in various styles and sizes, it’s the perfect foundation for restful nights and stylish interiors.",
        category: "Furniture",
        filter: "furnitur",
    },
    {
        name: "Furniture Bed",
        //   image: bed1,
        //   price: 11200.0,
        description: "The Bed is a stylish centerpiece that combines comfort and design. Crafted for durability, it offers a cozy sleeping experience while enhancing your bedroom decor. Available in various styles and sizes, it’s the perfect foundation for restful nights and stylish interiors.",
        category: "Furniture",
        filter: "furnitur",
    },
    {
        name: "Furniture Bed",
        //   image: bed2,
        //   price: 11200.0,
        description: "The Bed is a stylish centerpiece that combines comfort and design. Crafted for durability, it offers a cozy sleeping experience while enhancing your bedroom decor. Available in various styles and sizes, it’s the perfect foundation for restful nights and stylish interiors.",
        category: "Furniture",
        filter: "furnitur",
    },
    {
        name: "Furniture Bed",
        //   image: bed3,
        //   price: 11200.0,
        description: "The Bed is a stylish centerpiece that combines comfort and design. Crafted for durability, it offers a cozy sleeping experience while enhancing your bedroom decor. Available in various styles and sizes, it’s the perfect foundation for restful nights and stylish interiors.",
        category: "Furniture",
        filter: "furnitur",
    },
    {
        name: "Furniture Bed",
        //   image: bed4,
        //   price: 11200.0,
        description: "The Bed is a stylish centerpiece that combines comfort and design. Crafted for durability, it offers a cozy sleeping experience while enhancing your bedroom decor. Available in various styles and sizes, it’s the perfect foundation for restful nights and stylish interiors.",
        category: "Furniture",
        filter: "furnitur",
    },

    // furniture chair
    {
        name: "Furniture Chair",
          image: chair4,
        price: 11200.0,
        description: "The Chair is a chic and comfortable seating option that adds flair to any room. Designed for both style and functionality, it offers ergonomic support and a range of finishes to complement your decor. Perfect for relaxing or entertaining, this chair enhances your space with elegance and practicality.",
        category: "Furniture",
        filter: "furnitur",
    },
    {
        name: "Furniture Chair",
          image: chair,
        price: 11200.0,
        description: "The Chair is a chic and comfortable seating option that adds flair to any room. Designed for both style and functionality, it offers ergonomic support and a range of finishes to complement your decor. Perfect for relaxing or entertaining, this chair enhances your space with elegance and practicality.",
        category: "Furniture",
        filter: "furnitur",
    },
    {
        name: "Furniture Chair",
          image: chair1,
        price: 11200.0,
        description: "The Chair is a chic and comfortable seating option that adds flair to any room. Designed for both style and functionality, it offers ergonomic support and a range of finishes to complement your decor. Perfect for relaxing or entertaining, this chair enhances your space with elegance and practicality.",
        category: "Furniture",
        filter: "furnitur",
    },
    {
        name: "Furniture Chair",
          image: chair2,
        price: 11200.0,
        description: "The Chair is a chic and comfortable seating option that adds flair to any room. Designed for both style and functionality, it offers ergonomic support and a range of finishes to complement your decor. Perfect for relaxing or entertaining, this chair enhances your space with elegance and practicality.",
        category: "Furniture",
        filter: "furnitur",
    },
    {
        name: "Furniture Chair",
          image: chair3,
        price: 11200.0,
        description: "The Chair is a chic and comfortable seating option that adds flair to any room. Designed for both style and functionality, it offers ergonomic support and a range of finishes to complement your decor. Perfect for relaxing or entertaining, this chair enhances your space with elegance and practicality.",
        category: "Furniture",
        filter: "furnitur",
    },

    // furniture sofas
    {
        name: "Furniture Sofa",
          image: sofa,
        //   price: 11200.0,
        description: "The Sofa is a stylish and inviting centerpiece for your living space. Designed for comfort and durability, it offers ample seating and a range of colors and fabrics to suit any decor. Perfect for relaxing, entertaining, or cozy movie nights, this sofa enhances your home’s aesthetic while providing a welcoming atmosphere.",
        category: "Furniture",
        filter: "furnitur",
    },
    {
        name: "Furniture Sofa",
          image: sofa1,
        price: 11200.0,
        description: "The Sofa is a stylish and inviting centerpiece for your living space. Designed for comfort and durability, it offers ample seating and a range of colors and fabrics to suit any decor. Perfect for relaxing, entertaining, or cozy movie nights, this sofa enhances your home’s aesthetic while providing a welcoming atmosphere.",
        category: "Furniture",
        filter: "furnitur",
    },
    {
        name: "Furniture Sofa",
          image: sofa2,
        price: 11200.0,
        description: "The Sofa is a stylish and inviting centerpiece for your living space. Designed for comfort and durability, it offers ample seating and a range of colors and fabrics to suit any decor. Perfect for relaxing, entertaining, or cozy movie nights, this sofa enhances your home’s aesthetic while providing a welcoming atmosphere.",
        category: "Furniture",
        filter: "furnitur",
    },
    {
        name: "Furniture Sofa",
          image: sofa3,
        price: 11200.0,
        description: "The Sofa is a stylish and inviting centerpiece for your living space. Designed for comfort and durability, it offers ample seating and a range of colors and fabrics to suit any decor. Perfect for relaxing, entertaining, or cozy movie nights, this sofa enhances your home’s aesthetic while providing a welcoming atmosphere.",
        category: "Furniture",
        filter: "furnitur",
    },
    {
        name: "Furniture Sofa",
          image: sofa4,
        price: 11200.0,
        description: "The Sofa is a stylish and inviting centerpiece for your living space. Designed for comfort and durability, it offers ample seating and a range of colors and fabrics to suit any decor. Perfect for relaxing, entertaining, or cozy movie nights, this sofa enhances your home’s aesthetic while providing a welcoming atmosphere.",
        category: "Furniture",
        filter: "furnitur",
    },

    // furniture storage
    {
        name: "Furniture Storage",
          image: storage,
        price: 11200.0,
        description: "The Storage Solution is a practical and stylish way to keep your space organized. Featuring various sizes and designs, it offers ample room for all your essentials while enhancing your decor. Perfect for any room, this storage option combines functionality with aesthetic appeal, making it easy to declutter and beautify your home.",
        category: "Furniture",
        filter: "furnitur",
    },
    {
        name: "Furniture Storage",
          image: storage1,
        price: 11200.0,
        description: "The Storage Solution is a practical and stylish way to keep your space organized. Featuring various sizes and designs, it offers ample room for all your essentials while enhancing your decor. Perfect for any room, this storage option combines functionality with aesthetic appeal, making it easy to declutter and beautify your home.",
        category: "Furniture",
        filter: "furnitur",
    },
    {
        name: "Furniture Storage",
          image: storage2,
        price: 11200.0,
        description: "The Storage Solution is a practical and stylish way to keep your space organized. Featuring various sizes and designs, it offers ample room for all your essentials while enhancing your decor. Perfect for any room, this storage option combines functionality with aesthetic appeal, making it easy to declutter and beautify your home.",
        category: "Furniture",
        filter: "furnitur",
    },
    {
        name: "Furniture Storage",
          image: storage3,
        price: 11200.0,
        description: "The Storage Solution is a practical and stylish way to keep your space organized. Featuring various sizes and designs, it offers ample room for all your essentials while enhancing your decor. Perfect for any room, this storage option combines functionality with aesthetic appeal, making it easy to declutter and beautify your home.",
        category: "Furniture",
        filter: "furnitur",
    },
    {
        name: "Furniture Storage",
          image: storage4,
        price: 11200.0,
        description: "The Storage Solution is a practical and stylish way to keep your space organized. Featuring various sizes and designs, it offers ample room for all your essentials while enhancing your decor. Perfect for any room, this storage option combines functionality with aesthetic appeal, making it easy to declutter and beautify your home.",
        category: "Furniture",
        filter: "furnitur",
    },

    // furniture tables
    {
        name: "Furniture Tables",
          image: table,
        price: 11200.0,
        description: "The Table is a versatile piece that serves as the heart of your space. Whether for dining, working, or displaying decor, it combines style and functionality. Available in various materials and designs, this table enhances your decor while providing a practical surface for everyday use. Perfect for gatherings or quiet moments, it adds charm and utility to any room.",
        category: "Furniture",
        filter: "furnitur",
    },
    {
        name: "Furniture Tables",
          image: table1,
        price: 11200.0,
        description: "The Table is a versatile piece that serves as the heart of your space. Whether for dining, working, or displaying decor, it combines style and functionality. Available in various materials and designs, this table enhances your decor while providing a practical surface for everyday use. Perfect for gatherings or quiet moments, it adds charm and utility to any room.",
        category: "Furniture",
        filter: "furnitur",
    },
    {
        name: "Furniture Tables",
          image: table2,
        price: 11200.0,
        description: "The Table is a versatile piece that serves as the heart of your space. Whether for dining, working, or displaying decor, it combines style and functionality. Available in various materials and designs, this table enhances your decor while providing a practical surface for everyday use. Perfect for gatherings or quiet moments, it adds charm and utility to any room.",
        category: "Furniture",
        filter: "furnitur",
    },
    {
        name: "Furniture Tables",
          image: table3,
        price: 11200.0,
        description: "The Table is a versatile piece that serves as the heart of your space. Whether for dining, working, or displaying decor, it combines style and functionality. Available in various materials and designs, this table enhances your decor while providing a practical surface for everyday use. Perfect for gatherings or quiet moments, it adds charm and utility to any room.",
        category: "Furniture",
        filter: "furnitur",
    },
    {
        name: "Furniture Tables",
          image: table4,
        price: 11200.0,
        description: "The Table is a versatile piece that serves as the heart of your space. Whether for dining, working, or displaying decor, it combines style and functionality. Available in various materials and designs, this table enhances your decor while providing a practical surface for everyday use. Perfect for gatherings or quiet moments, it adds charm and utility to any room.",
        category: "Furniture",
        filter: "furnitur",
    },

    // kitchen backsplashes
    {
        name: "kitchen backsplashes",
          image: backsplash,
        price: 11200.0,
        description: "The Kitchen Backsplash is a stylish and protective element that enhances your cooking space. Available in a variety of materials, colors, and patterns, it adds a decorative touch while safeguarding walls from splashes and stains. Easy to clean and maintain, this backsplash not only elevates your kitchen's aesthetic but also combines functionality with design, making it an essential feature for any modern kitchen.",
        category: "Kitchen",
        filter: "kitchen",
    },
    {
        name: "kitchen backsplashes",
          image: backsplash1,
        price: 11200.0,
        description: "The Kitchen Backsplash is a stylish and protective element that enhances your cooking space. Available in a variety of materials, colors, and patterns, it adds a decorative touch while safeguarding walls from splashes and stains. Easy to clean and maintain, this backsplash not only elevates your kitchen's aesthetic but also combines functionality with design, making it an essential feature for any modern kitchen.",
        category: "Kitchen",
        filter: "kitchen",
    },
    {
        name: "kitchen backsplashes",
          image: backsplash2,
        price: 11200.0,
        description: "The Kitchen Backsplash is a stylish and protective element that enhances your cooking space. Available in a variety of materials, colors, and patterns, it adds a decorative touch while safeguarding walls from splashes and stains. Easy to clean and maintain, this backsplash not only elevates your kitchen's aesthetic but also combines functionality with design, making it an essential feature for any modern kitchen.",
        category: "Kitchen",
        filter: "kitchen",
    },
    {
        name: "kitchen backsplashes",
          image: backsplash3,
        price: 11200.0,
        description: "The Kitchen Backsplash is a stylish and protective element that enhances your cooking space. Available in a variety of materials, colors, and patterns, it adds a decorative touch while safeguarding walls from splashes and stains. Easy to clean and maintain, this backsplash not only elevates your kitchen's aesthetic but also combines functionality with design, making it an essential feature for any modern kitchen.",
        category: "Kitchen",
        filter: "kitchen",
    },
    {
        name: "kitchen backsplashes",
          image: backsplash4,
        price: 11200.0,
        description: "The Kitchen Backsplash is a stylish and protective element that enhances your cooking space. Available in a variety of materials, colors, and patterns, it adds a decorative touch while safeguarding walls from splashes and stains. Easy to clean and maintain, this backsplash not only elevates your kitchen's aesthetic but also combines functionality with design, making it an essential feature for any modern kitchen.",
        category: "Kitchen",
        filter: "kitchen",
    },

    // kitchen cabinets
    {
        name: "kitchen cabinets",
          image:  cabinets1,
        price: 11200.0,
        description: "Kitchen Cabinets are essential storage solutions that combine style and functionality. Available in various materials, finishes, and designs, they enhance your kitchen's aesthetic while providing ample space for organization. With features like soft-close doors and customizable interiors, these cabinets offer practicality and elegance, making them a vital part of any kitchen renovation.",
        category: "Kitchen",
        filter: "kitchen",
    },
    {
        name: "kitchen cabinets",
          image:  cabinets2,
        price: 11200.0,
        description: "Kitchen Cabinets are essential storage solutions that combine style and functionality. Available in various materials, finishes, and designs, they enhance your kitchen's aesthetic while providing ample space for organization. With features like soft-close doors and customizable interiors, these cabinets offer practicality and elegance, making them a vital part of any kitchen renovation.",
        category: "Kitchen",
        filter: "kitchen",
    },
    {
        name: "kitchen cabinets",
          image:  cabinets3,
        price: 11200.0,
        description: "Kitchen Cabinets are essential storage solutions that combine style and functionality. Available in various materials, finishes, and designs, they enhance your kitchen's aesthetic while providing ample space for organization. With features like soft-close doors and customizable interiors, these cabinets offer practicality and elegance, making them a vital part of any kitchen renovation.",
        category: "Kitchen",
        filter: "kitchen",
    },
    {
        name: "kitchen cabinets",
          image:  cabinets4,
        price: 11200.0,
        description: "Kitchen Cabinets are essential storage solutions that combine style and functionality. Available in various materials, finishes, and designs, they enhance your kitchen's aesthetic while providing ample space for organization. With features like soft-close doors and customizable interiors, these cabinets offer practicality and elegance, making them a vital part of any kitchen renovation.",
        category: "Kitchen",
        filter: "kitchen",
    },
    {
        name: "kitchen cabinets",
          // image:  cabinets,
        price: 11200.0,
        description: "Kitchen Cabinets are essential storage solutions that combine style and functionality. Available in various materials, finishes, and designs, they enhance your kitchen's aesthetic while providing ample space for organization. With features like soft-close doors and customizable interiors, these cabinets offer practicality and elegance, making them a vital part of any kitchen renovation.",
        category: "Kitchen",
        filter: "kitchen",
    },

    // kitchen countertops
    {
        name: "kitchen Countertops",
          image:  countertops,
        price: 11200.0,
        description: "Kitchen Countertops are durable surfaces that enhance your cooking space. Available in various materials like granite and quartz, they offer both style and functionality. Easy to clean and resistant to stains, these countertops are essential for a modern kitchen.",
        category: "Kitchen",
        filter: "kitchen",
    },
    {
        name: "kitchen Countertops",
          image:  countertops1,
        price: 11200.0,
        description: "Kitchen Countertops are durable surfaces that enhance your cooking space. Available in various materials like granite and quartz, they offer both style and functionality. Easy to clean and resistant to stains, these countertops are essential for a modern kitchen.",
        category: "Kitchen",
        filter: "kitchen",
    },
    {
        name: "kitchen Countertops",
          image:  countertops2,
        price: 11200.0,
        description: "Kitchen Countertops are durable surfaces that enhance your cooking space. Available in various materials like granite and quartz, they offer both style and functionality. Easy to clean and resistant to stains, these countertops are essential for a modern kitchen.",
        category: "Kitchen",
        filter: "kitchen",
    },
    {
        name: "kitchen Countertops",
          image:  countertops3,
        price: 11200.0,
        description: "Kitchen Countertops are durable surfaces that enhance your cooking space. Available in various materials like granite and quartz, they offer both style and functionality. Easy to clean and resistant to stains, these countertops are essential for a modern kitchen.",
        category: "Kitchen",
        filter: "kitchen",
    },
    {
        name: "kitchen Countertops",
          image:  countertops4,
        price: 11200.0,
        description: "Kitchen Countertops are durable surfaces that enhance your cooking space. Available in various materials like granite and quartz, they offer both style and functionality. Easy to clean and resistant to stains, these countertops are essential for a modern kitchen.",
        category: "Kitchen",
        filter: "kitchen",
    },

    // kitchen island
    {
        name: "kitchen island",
          image: island,
        price: 11200.0,
        description: "The Kitchen Island is a versatile centerpiece that adds both style and functionality. Providing extra counter space and storage, it’s perfect for meal prep and entertaining. Available in various designs and finishes, the island enhances your kitchen’s aesthetic while serving as a social hub for family and friends.",
        category: "Kitchen",
        filter: "kitchen",
    },
    {
        name: "kitchen island",
          image: island1,
        price: 11200.0,
        description: "The Kitchen Island is a versatile centerpiece that adds both style and functionality. Providing extra counter space and storage, it’s perfect for meal prep and entertaining. Available in various designs and finishes, the island enhances your kitchen’s aesthetic while serving as a social hub for family and friends.",
        category: "Kitchen",
        filter: "kitchen",
    },
    {
        name: "kitchen island",
          image: island2,
        price: 11200.0,
        description: "The Kitchen Island is a versatile centerpiece that adds both style and functionality. Providing extra counter space and storage, it’s perfect for meal prep and entertaining. Available in various designs and finishes, the island enhances your kitchen’s aesthetic while serving as a social hub for family and friends.",
        category: "Kitchen",
        filter: "kitchen",
    },
    {
        name: "kitchen island",
          image: island3,
        price: 11200.0,
        description: "The Kitchen Island is a versatile centerpiece that adds both style and functionality. Providing extra counter space and storage, it’s perfect for meal prep and entertaining. Available in various designs and finishes, the island enhances your kitchen’s aesthetic while serving as a social hub for family and friends.",
        category: "Kitchen",
        filter: "kitchen",
    },
    {
        name: "kitchen island",
          image: island4,
        price: 11200.0,
        description: "The Kitchen Island is a versatile centerpiece that adds both style and functionality. Providing extra counter space and storage, it’s perfect for meal prep and entertaining. Available in various designs and finishes, the island enhances your kitchen’s aesthetic while serving as a social hub for family and friends.",
        category: "Kitchen",
        filter: "kitchen",
    },

    // kitchen faucets
    {
        name: "kitchen Faucets",
          image: faucets,
        price: 11200.0,
        description: "Kitchen Faucets are essential fixtures that combine style and functionality. They provide convenient water access while enhancing your kitchen decor. With features like pull-down sprayers and touchless controls, these faucets make cooking and cleaning tasks easier and more efficient.",
        category: "Kitchen",
        filter: "kitchen",
    },
    {
        name: "kitchen Faucets",
          image: faucets1,
        price: 11200.0,
        description: "Kitchen Faucets are essential fixtures that combine style and functionality. They provide convenient water access while enhancing your kitchen decor. With features like pull-down sprayers and touchless controls, these faucets make cooking and cleaning tasks easier and more efficient.",
        category: "Kitchen",
        filter: "kitchen",
    },
    {
        name: "kitchen Faucets",
          image: faucets2,
        price: 11200.0,
        description: "Kitchen Faucets are essential fixtures that combine style and functionality. They provide convenient water access while enhancing your kitchen decor. With features like pull-down sprayers and touchless controls, these faucets make cooking and cleaning tasks easier and more efficient.",
        category: "Kitchen",
        filter: "kitchen",
    },
    {
        name: "kitchen Faucets",
          image: faucets3,
        price: 11200.0,
        description: "Kitchen Faucets are essential fixtures that combine style and functionality. They provide convenient water access while enhancing your kitchen decor. With features like pull-down sprayers and touchless controls, these faucets make cooking and cleaning tasks easier and more efficient.",
        category: "Kitchen",
        filter: "kitchen",
    },
    {
        name: "kitchen Faucets",
          image: faucets4,
        price: 11200.0,
        description: "Kitchen Faucets are essential fixtures that combine style and functionality. They provide convenient water access while enhancing your kitchen decor. With features like pull-down sprayers and touchless controls, these faucets make cooking and cleaning tasks easier and more efficient.",
        category: "Kitchen",
        filter: "kitchen",
    },

    // lighting ceiling
    {
        name: "ceiling light",
          image: lights,
        price: 11200.0,
        description: "Ceiling Lights are essential fixtures that provide overall illumination while enhancing your decor. Available in various styles and designs, they combine functionality with aesthetic appeal. Perfect for any space, they create a bright and inviting atmosphere.",
        category: "Lights",
        filter: "lights",
    },
    {
        name: "ceiling light",
          image: lights1,
        price: 11200.0,
        description: "Ceiling Lights are essential fixtures that provide overall illumination while enhancing your decor. Available in various styles and designs, they combine functionality with aesthetic appeal. Perfect for any space, they create a bright and inviting atmosphere.",
        category: "Lights",
        filter: "lights",
    },
    {
        name: "ceiling light",
          image: lights2,
        price: 11200.0,
        description: "Ceiling Lights are essential fixtures that provide overall illumination while enhancing your decor. Available in various styles and designs, they combine functionality with aesthetic appeal. Perfect for any space, they create a bright and inviting atmosphere.",
        category: "Lights",
        filter: "lights",
    },
    {
        name: "ceiling light",
          image: lights3,
        price: 11200.0,
        description: "Ceiling Lights are essential fixtures that provide overall illumination while enhancing your decor. Available in various styles and designs, they combine functionality with aesthetic appeal. Perfect for any space, they create a bright and inviting atmosphere.",
        category: "Lights",
        filter: "lights",
    },
    {
        name: "ceiling light",
          image: lights4,
        price: 11200.0,
        description: "Ceiling Lights are essential fixtures that provide overall illumination while enhancing your decor. Available in various styles and designs, they combine functionality with aesthetic appeal. Perfect for any space, they create a bright and inviting atmosphere.",
        category: "Lights",
        filter: "lights",
    },

    // Floor lights
    {
        name: "Floor light",
          image: floorlamps,
        price: 11200.0,
        description: "Floor Lights are versatile fixtures that add both style and illumination to any room. Ideal for accent lighting or creating ambiance, they come in various designs to suit your decor. Perfect for living spaces, they provide a warm glow while enhancing your home's aesthetic.",
        category: "Lights",
        filter: "lights",
    },
    {
        name: "Floor light",
          image: floorlamps1,
        price: 11200.0,
        description: "Floor Lights are versatile fixtures that add both style and illumination to any room. Ideal for accent lighting or creating ambiance, they come in various designs to suit your decor. Perfect for living spaces, they provide a warm glow while enhancing your home's aesthetic.",
        category: "Lights",
        filter: "lights",
    },
    {
        name: "Floor light",
          image: floorlamps2,
        price: 11200.0,
        description: "Floor Lights are versatile fixtures that add both style and illumination to any room. Ideal for accent lighting or creating ambiance, they come in various designs to suit your decor. Perfect for living spaces, they provide a warm glow while enhancing your home's aesthetic.",
        category: "Lights",
        filter: "lights",
    },
    {
        name: "Floor light",
          image: floorlamps3,
        price: 11200.0,
        description: "Floor Lights are versatile fixtures that add both style and illumination to any room. Ideal for accent lighting or creating ambiance, they come in various designs to suit your decor. Perfect for living spaces, they provide a warm glow while enhancing your home's aesthetic.",
        category: "Lights",
        filter: "lights",
    },
    {
        name: "Floor light",
          image: floorlamps4,
        price: 11200.0,
        description: "Floor Lights are versatile fixtures that add both style and illumination to any room. Ideal for accent lighting or creating ambiance, they come in various designs to suit your decor. Perfect for living spaces, they provide a warm glow while enhancing your home's aesthetic.",
        category: "Lights",
        filter: "lights",
    },

    // outdoor lights
    {
        name: "outdoor light",
          image:  outdoorlamps,
        price: 11200.0,
        description: "Outdoor Lights enhance safety and ambiance in your outdoor spaces. Available in various styles, they illuminate pathways, patios, and gardens while adding aesthetic appeal. Perfect for creating a welcoming atmosphere, they make your outdoor areas enjoyable after dark.",
        category: "Lights",
        filter: "lights",
    },
    {
        name: "outdoor light",
          image:  outdoorlamps1,
        price: 11200.0,
        description: "Outdoor Lights enhance safety and ambiance in your outdoor spaces. Available in various styles, they illuminate pathways, patios, and gardens while adding aesthetic appeal. Perfect for creating a welcoming atmosphere, they make your outdoor areas enjoyable after dark.",
        category: "Lights",
        filter: "lights",
    },
    {
        name: "outdoor light",
          image:  outdoorlamps2,
        price: 11200.0,
        description: "Outdoor Lights enhance safety and ambiance in your outdoor spaces. Available in various styles, they illuminate pathways, patios, and gardens while adding aesthetic appeal. Perfect for creating a welcoming atmosphere, they make your outdoor areas enjoyable after dark.",
        category: "Lights",
        filter: "lights",
    },
    {
        name: "outdoor light",
          image:  outdoorlamps3,
        price: 11200.0,
        description: "Outdoor Lights enhance safety and ambiance in your outdoor spaces. Available in various styles, they illuminate pathways, patios, and gardens while adding aesthetic appeal. Perfect for creating a welcoming atmosphere, they make your outdoor areas enjoyable after dark.",
        category: "Lights",
        filter: "lights",
    },
    {
        name: "outdoor light",
          image:  outdoorlamps4,
        price: 11200.0,
        description: "Outdoor Lights enhance safety and ambiance in your outdoor spaces. Available in various styles, they illuminate pathways, patios, and gardens while adding aesthetic appeal. Perfect for creating a welcoming atmosphere, they make your outdoor areas enjoyable after dark.",
        category: "Lights",
        filter: "lights",
    },

    // table lamps
    {
        name: "Table lamps",
          image: tablelamps,
        price: 11200.0,
        description: "Table Lamps are stylish fixtures that provide focused lighting and enhance your decor. Available in various designs and sizes, they add warmth and character to any room. Perfect for reading or creating ambiance, these lamps are both functional and decorative.",
        category: "Lights",
        filter: "lights",
    },
    {
        name: "Table lamps",
          image: tablelamps1,
        price: 11200.0,
        description: "Table Lamps are stylish fixtures that provide focused lighting and enhance your decor. Available in various designs and sizes, they add warmth and character to any room. Perfect for reading or creating ambiance, these lamps are both functional and decorative.",
        category: "Lights",
        filter: "lights",
    },
    {
        name: "Table lamps",
          image: tablelamps2,
        price: 11200.0,
        description: "Table Lamps are stylish fixtures that provide focused lighting and enhance your decor. Available in various designs and sizes, they add warmth and character to any room. Perfect for reading or creating ambiance, these lamps are both functional and decorative.",
        category: "Lights",
        filter: "lights",
    },
    {
        name: "Table lamps",
          image: tablelamps3,
        price: 11200.0,
        description: "Table Lamps are stylish fixtures that provide focused lighting and enhance your decor. Available in various designs and sizes, they add warmth and character to any room. Perfect for reading or creating ambiance, these lamps are both functional and decorative.",
        category: "Lights",
        filter: "lights",
    },
    {
        name: "Table lamps",
          image: tablelamps4,
        price: 11200.0,
        description: "Table Lamps are stylish fixtures that provide focused lighting and enhance your decor. Available in various designs and sizes, they add warmth and character to any room. Perfect for reading or creating ambiance, these lamps are both functional and decorative.",
        category: "Lights",
        filter: "lights",
    },

    // wall lights
    {
        name: "wall lights",
          image: walllights,
        price: 11200.0,
        description: "Wall Lights are versatile fixtures that add both illumination and style to your space. Available in a range of designs, they can serve as accent lighting or provide general illumination. Perfect for hallways, living rooms, or bedrooms, they enhance your decor while saving floor space.",
        category: "Lights",
        filter: "lights",
    },
    {
        name: "wall lights",
          // image: walllights4,
        price: 11200.0,
        description: "Wall Lights are versatile fixtures that add both illumination and style to your space. Available in a range of designs, they can serve as accent lighting or provide general illumination. Perfect for hallways, living rooms, or bedrooms, they enhance your decor while saving floor space.",
        category: "Lights",
        filter: "lights",
    },
    {
        name: "wall lights",
          image: walllights1,
        price: 11200.0,
        description: "Wall Lights are versatile fixtures that add both illumination and style to your space. Available in a range of designs, they can serve as accent lighting or provide general illumination. Perfect for hallways, living rooms, or bedrooms, they enhance your decor while saving floor space.",
        category: "Lights",
        filter: "lights",
    },
    {
        name: "wall lights",
          // image: walllights2,
        price: 11200.0,
        description: "Wall Lights are versatile fixtures that add both illumination and style to your space. Available in a range of designs, they can serve as accent lighting or provide general illumination. Perfect for hallways, living rooms, or bedrooms, they enhance your decor while saving floor space.",
        category: "Lights",
        filter: "lights",
    },
    {
        name: "wall lights",
          // image: walllight3s,
        price: 11200.0,
        description: "Wall Lights are versatile fixtures that add both illumination and style to your space. Available in a range of designs, they can serve as accent lighting or provide general illumination. Perfect for hallways, living rooms, or bedrooms, they enhance your decor while saving floor space.",
        category: "Lights",
        filter: "lights",
    },

];
